### ISSUE TITLE
http error signature not valid

### ISSUE THREAD

**Issue by clearsolutions** [semashkinvg/Bitmex.NET#1]
On bitmex testnet everything works perfect.
I wanted to use this on a real bitmex account so:

Generated new api key
Set {BitmexEnvironment.Prod, "https://bitmex.com"} instead of testnet 
Change the env to .Prod 

As soon as I want to make an authenticated request it gives me the error: 
http error signature not valid

If I check the value of nonce, message and bytearray I get:
nonce is : 8935330312157344
message is : POST/api/v1/position/leverage{"symbol":"XBTUSD","leverage":50.0}8935330312157344
bytearray is : 95b2d43d54dbc62dfb1b1457dbce27bb456d9b9c4366da124259ce980ce8f12f

I generated multiple new api keys but I keep getting the same error,

best regards,
Jens

**Comment by semashkinvg** [comment]
Thank you for you post! I will definitely have a look and get back to you soon

**Comment by semashkinvg** [comment]
@clearsolutions  please find fixed version here https://www.nuget.org/packages/Bitmex.NET/1.0.2.25211
