### ISSUE TITLE
Implement and test BitmexApiUrls.Stats

### ISSUE THREAD

**Issue by semashkinvg** [semashkinvg/Bitmex.NET#11]
As a developer, I should have access to the stats information through the REST API /stats/*

TODO:
uncomment fields under BitmexApiUrls.Stats
fix dtos for the user API requests
add at least 1 integration test for each REST call

**Comment by ridicoulous** [comment]
I will do it

**Comment by semashkinvg** [comment]
@ridicoulous that would be nice :)
Thanks,
