### ISSUE TITLE
Implement and test BitmexApiUrls.Leaderboard

### ISSUE THREAD

**Issue by semashkinvg** [semashkinvg/Bitmex.NET#12]
As a developer, I should have access to the Leaderboard information through the REST API /leaderboard/*

TODO:
uncomment fields under BitmexApiUrls.Leaderboard
fix dtos for the user API requests
add at least 1 integration test for each REST call

**Comment by ridicoulous** [comment]
And it=)

**Comment by semashkinvg** [comment]
@ridicoulous make sure that you make all done according to this api description
https://github.com/BitMEX/api-connectors/tree/master/auto-generated/csharp
