### ISSUE TITLE
Implement and test BitmexApiUrls.Notification&Liquidation&Funding

### ISSUE THREAD

**Issue by semashkinvg** [semashkinvg/Bitmex.NET#13]
As a developer, I should have access to the Leaderboard information through the REST API /notification/, /liquidation/, /funding/

TODO:
uncomment fields under BitmexApiUrls.Notification&Liquidation&Funding
fix dtos for the user API requests
add at least 1 integration test for each REST call

**Comment by ridicoulous** [comment]
Notification and Liquidation in progress

**Comment by semashkinvg** [comment]
@ridicoulous how the things are? You still going to finish it, aren't you?

**Comment by ridicoulous** [comment]
Sorry, i’m on vacation without good internet. Will have time tomorrow
