### ISSUE TITLE
Implement and Test WebSocket.Order

### ISSUE THREAD

**Issue by semashkinvg** [semashkinvg/Bitmex.NET#17]
as a developer, I want to be able to sign on order live updates

TODO:
1) New subscription in BitmetSocketSubscriptions
2) Test that shows that subscription works
3) Use models from REST API, if web scoket model is different - create a new one under Models/Socket

**Comment by MaDeRkAn** [comment]
Do you still need help ? As I see there is already order subscription on socket.

**Comment by semashkinvg** [comment]
@MaDeRkAn looks like it was done, closing...
