### ISSUE TITLE
TradeSocketSubscription - Bug

### ISSUE THREAD

**Issue by diplinfmarkodrews** [semashkinvg/Bitmex.NET#22]
Hi,

there seems to be a problem with the Tradesocket.
Whenever I suscribe to TradeSocket, I get Exception.
The grossValue is null, not valid for decimals and therefor, the TradeDto can not be constructed from JToken.

How to prevent this from happening?

**Comment by semashkinvg** [comment]
@diplinfmarkodrews 

thank you for the information! I will get it fixed soon
Cheers,
