### ISSUE TITLE
Serialization Bug for Booleans

### ISSUE THREAD

**Issue by MaDeRkAn** [semashkinvg/Bitmex.NET#24]
I get partial candles even if I set Partial as false at TradeBucketedGETRequestParams. 
Then I have checked logs and the request was:
https://www.bitmex.com/api/v1/trade/bucketed?binSize=5m&partial=False&symbol=XRPZ18&columns=&count=500&start=&reverse=False&startTime=&endTime=

as you can see booleans starts with uppercase letter "False".  Bitmex accept as true  anything other than "false". Therefore when we de-serialize object to request params, lowercase letters have to be used.

The project framework is .Net Core 2.1

**Comment by semashkinvg** [comment]
hi @MaDeRkAn, 
thanks, will have a look soon

**Comment by semashkinvg** [comment]
rather quaint behaviour... try to push a new version next morning! thank you one more time for noting this issue

**Comment by semashkinvg** [comment]
hey, pushed 2.0.70  nuget package version  with this fix
let me know if any other issues
