### ISSUE TITLE
Implement and Tests WebSocket.announcement

### ISSUE THREAD

**Issue by semashkinvg** [semashkinvg/Bitmex.NET#27]
as a developer, I want to be able to sign on anouncements

TODO:
1) New subscription in BitmetSocketSubscriptions
2) Test that shows that subscription works
3) Use models from REST API, if web scoket model is different - create a new one under Models/Socket

**Comment by MaDeRkAn** [comment]
I have just implemented connection test not get data test. Because the announcements are very rare.
