### ISSUE TITLE
.net Standard version

### ISSUE THREAD

**Issue by andrzej-suwala** [semashkinvg/Bitmex.NET#3]
Hi !

It would be excellent if your great lib was compatible with .net standard 2.0.
Right now it's targeting .net 4.5, but it was working in .net standard if I cloned sources and compiled them myself.
But now the lib is using WebSocketSharp 1.0.3-rc11
and it doesn't run in .net standard.

I would be very gratefull if you would port your great lib to the .net standard.

Thanks :)

**Comment by semashkinvg** [comment]
Much appreciate your feedback. I'm going to finish web sockets firstly and your request will be next

**Comment by andrzej-suwala** [comment]
Great, thanks :-)

**Comment by semashkinvg** [comment]
Hi, this issue has been completed within WebSocket project (see the card https://github.com/semashkinvg/Bitmex.NET/projects/1#card-9972829). I've changed web socket lib, so feel free using it with .Net Standard
