### ISSUE TITLE
BitmexApiException "Signature not valid". Mono

### ISSUE THREAD

**Issue by wa1one** [semashkinvg/Bitmex.NET#32]
I get BitmexApiException "Signature not valid" exception on all requests.

You have to provide Scheme to HttpRequestMessage. 

https://github.com/mono/mono/blob/1291c08c1d07b97ed7087d15f4eca2538bd5c24f/mcs/class/System.Net.Http/System.Net.Http/HttpRequestMessage.cs#L109

**Comment by semashkinvg** [comment]
hi @wa1one , thank you for the feedback. can you provide an example of how to reproduce this case?

**Comment by wa1one** [comment]
@semashkinvg all your tests are not working in Visual Studio for Mac.

**Comment by alex-lucid** [comment]
Can confirm, just run tests on VS for Mac

**Comment by alex-lucid** [comment]
Done [https://github.com/semashkinvg/Bitmex.NET/pull/33](https://github.com/semashkinvg/Bitmex.NET/pull/33)  sorry for a delay

**Comment by alex-lucid** [comment]
@semashkinvg please push latest to NuGet gallery from last build https://ci.appveyor.com/project/semashkinvg/bitmex-net/build/artifacts

**Comment by semashkinvg** [comment]
@alex-lucid it's been done. the new version will available very soon

Thanks for support guys, I currently don't have time to support this project. hopefully will get back soon
