### ISSUE TITLE
Can i trade with symbols: XBTZ18 or XBTН19

### ISSUE THREAD

**Issue by spbsmile** [semashkinvg/Bitmex.NET#34]
This is a common question.
Bitmex api allow trading in pairs XBTZ18 or XBTН19 ? 

![error](https://user-images.githubusercontent.com/4917689/53334535-30a3ad00-390a-11e9-89e0-5a5993a5d61c.png)

Thanks!

**Comment by spbsmile** [comment]
**upd**
XBTZ18 - old symbol. no use now.
XBTН19 - I do not know why api no work.

**Comment by semashkinvg** [comment]
@spbsmile hi, need to have a look

**Comment by alex-lucid** [comment]
If Symbol is supported on exchange, it will work

**Comment by semashkinvg** [comment]
@spbsmile  have this issue be resolved?

**Comment by spbsmile** [comment]
yes. thx
