### ISSUE TITLE
Propogate 503, 429 Error responses

### ISSUE THREAD

**Issue by HA07Z7XE** [semashkinvg/Bitmex.NET#35]
Bitmex returns the following errors in response to overload and rate limit caps respectively:
https://www.bitmex.com/app/restAPI

- 503 - The system is currently overloaded
- 429 - You have been rate limited. An additional header _Retry-After_ indicates the number of seconds you should wait before retrying.

Is there a way to propagate this information to the application, so it can handle them appropriately?

**Comment by alex-lucid** [comment]
Yes, just need to slightly extend [BitmexApiProxy.cs](https://github.com/semashkinvg/Bitmex.NET/blob/fd28dda89ae9af3efd6c95e71210f6b09824d115/Bitmex.NET/BitmexApiProxy.cs#L80) so that we can wrap such errors into special exception-classes so then you can catch and handle this on your consumer side

**Comment by semashkinvg** [comment]
@alex-lucid @HA07Z7XE Hi both, you would like to have different exception type for these codes, wouldn't you?

**Comment by HA07Z7XE** [comment]
Hi @semashkinvg , actually I have propagated the StatusCode itself through `BitmexApiException` so that my consuming code can handle and retry - https://github.com/semashkinvg/Bitmex.NET/pull/36 , https://github.com/HA07Z7XE/Bitmex.NET/commit/b722abcd58e8a3ae6e28d223f66f5a94a6929d39
(Sorry, I did not fix my PR because I do not have a  net462 environment).

My preference would be the same approach, as then other StatusCodes can also be handled from the client should the need arise.

**Comment by semashkinvg** [comment]
@HA07Z7XE ok, let me have a look how it could be approached

**Comment by semashkinvg** [comment]
@HA07Z7XE have a look at the commit attached to this issue, would it be sufficient in your case?

**Comment by HA07Z7XE** [comment]
@semashkinvg it would. If possible I would like to fix my PR which has the same changes. If I fix the CI build, does my PR look ok?

There are a few related (albiet breaking) changes in there around returning rate limit data which I also require,

**Comment by semashkinvg** [comment]
@HA07Z7XE  wow! you PR is just amazing, I dreamed to implement it half of year ago, but didn't have time to do this. Please proceed, that's absolutely great!

**Comment by semashkinvg** [comment]
@HA07Z7XE please run Integration tests with your own account (Api Key and secret) but don't commit them

**Comment by HA07Z7XE** [comment]
Sure. I'll get something up soon.
