### ISSUE TITLE
May I know if this library log its sent and received messages?

### ISSUE THREAD

**Issue by GitteryCoder** [semashkinvg/Bitmex.NET#5]
Hi semashkinvg,

I've browsed through the code and I can't figure out how logging is enabled / disabled for this .NET library. I often have to look at actual JSON strings sent in WebSocket to troubleshoot trading issues. So I am wondering if a logging facility is built-in.

If not, what is the best way for me to add in such a facility?

Thanks for providing open-sourcing this library!

**Comment by semashkinvg** [comment]
Hi @GitteryCoder, 
Thank you for your feedback, I'm going to add https://github.com/damianh/LibLog to make logging available for the most widespread logging frameworks!
Actually, I add this logging feature till the end of this week. let you know sure

Thanks,

**Comment by semashkinvg** [comment]
hi @GitteryCoder,
I'm happy to let you know that I added logging using LibLog, that means you can use the most famous logging frameworks such as NLog, Serilog and etc. For more information please check out [LibLog](https://github.com/damianh/LibLog)
Also, please check the [example](https://github.com/semashkinvg/Bitmex.NET/tree/master/Bitmex.NET.Example) within the repository, it will give you an idea how it would work in your solution and help you to set up appropriate logging level.

I'm opened for suggestions about how to improve the lib.

I'm gonna push this version into nuget quite soon.

Thanks,

**Comment by miqteam** [comment]
Hi,
How can i import custom logger implementation?
