### ISSUE TITLE
Expires time calculation (previously nonce) must be in future

### ISSUE THREAD

**Issue by tekr** [semashkinvg/Bitmex.NET#7]
Commit 4e0c4b343791a06ca7253970510e2b02bf1f673f changed the authentication mechanism from using nonces (problematic in multi-threaded use) to the more-recently-supported 'expires-time' mechanism, however it passes in the current client time as the expiry time. As such, Bitmex may reject the request as expired.

**Comment by semashkinvg** [comment]
hi @tekr ,
Thank you for the feedback. Actually, I'm not quite sure what you suppose to do and what's the better solution for that. The thing is, previously Bitmex accepted nonce in milliseconds, currently, it expects nonce in seconds. That was the reason for the change.
However, there is a little bug in this commit `new DateTime(1990, 1, 1);` should be `new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);`, but i'm going to fix that soon!

Thanks,

**Comment by tekr** [comment]
No worries. Actually I wondered the same before I committed my fix, and did check against the same code as you specified (I.e. specifying the DateTimeKind as UTC) but there was no difference.
I think you'll find both give the same result. 

Cheers
Matt. 

 
 
  On Wed, 18 Jul. 2018 at 22:13, semashkinvg<notifications@github.com> wrote:   
hi @tekr ,
Thank you for the feedback. Actually, I'm not quite sure what you suppose to do and what's the better solution for that. The thing is, previously Bitmex accepted nonce in milliseconds, currently, it expects nonce in seconds. That was the reason for the change.
However, there is a little bug in this commit new DateTime(1990, 1, 1); should be new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);, but i'm going to fix that soon!

Thanks,

**Comment by tekr** [comment]
Key point being, Bitmex now takes an expiry time for the message. As such, it needs to be in the future to avoid the possibility of it being rejected due to being out of date. 
 
 
  On Thu, 19 Jul. 2018 at 3:04, Matt<sonical2002@yahoo.com.au> wrote:   No worries. Actually I wondered the same before I committed my fix, and did check against the same code as you specified (I.e. specifying the DateTimeKind as UTC) but there was no difference.
I think you'll find both give the same result. 

Cheers
Matt. 

 
 
  On Wed, 18 Jul. 2018 at 22:13, semashkinvg<notifications@github.com> wrote:   
hi @tekr ,
Thank you for the feedback. Actually, I'm not quite sure what you suppose to do and what's the better solution for that. The thing is, previously Bitmex accepted nonce in milliseconds, currently, it expects nonce in seconds. That was the reason for the change.
However, there is a little bug in this commit new DateTime(1990, 1, 1); should be new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);, but i'm going to fix that soon!

Thanks,

**Comment by andrzej-suwala** [comment]
Yes, I'm getting the "This request has expired - `expires` is in the past. Current time: xxx", too.

Simple fix is to change NonceProvider: GetNonce() to:

`public long GetNonce()
        {
            return DateTimeOffset.UtcNow.ToUnixTimeSeconds()+2;
        }`

Well, it's working, but I'm not sure if it's OK with other logic of this (great) lib.

**Comment by semashkinvg** [comment]
hi @andrzej-suwala, @tekr,
The issue has been fixed and pretty soon I will push the new version to Nuget
